routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::get('/view-image', 'PreviewImageController@index')->name('view-image');

Auth::routes();

Route::group(['middleware' => 'auth'], function ()
{
	Route::get('/home', 'HomeController@index')->name('home');

    Route::group(['middleware' => 'roles', 'roles' => 'administrator'], function ()
    {
		Route::get('admin', 'Admin\AdminController@index');
		Route::resource('admin/roles', 'Admin\RolesController');
		Route::resource('admin/permissions', 'Admin\PermissionsController');
		Route::resource('admin/users', 'Admin\UsersController');
		Route::resource('admin/pages', 'Admin\PagesController');
		Route::resource('admin/activitylogs', 'Admin\ActivityLogsController')->only([
		    'index', 'show', 'destroy'
		]);
		Route::resource('admin/settings', 'Admin\SettingsController');
		Route::get('admin/generator', ['uses' => '\Appzcoder\LaravelAdmin\Controllers\ProcessController@getGenerator']);
		Route::post('admin/generator', ['uses' => '\Appzcoder\LaravelAdmin\Controllers\ProcessController@postGenerator']);
		Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');
	});

    Route::group(['middleware' => 'roles', 'roles' => 'admin'], function ()
    {
		Route::resource('artikel', 'ArtikelController');
    	Route::resource('banner', 'BannerController');
    	Route::resource('jasa', 'JasaController');
    	Route::resource('rekanan', 'RekananController');
    	Route::resource('setting-aplikasi', 'SettingAplikasiController');
    	Route::resource('setting-bengkel', 'SettingBengkelController');
    	Route::resource('user', 'UserController');
    });
});

app/Artikel.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use OwenIt\Auditing\Contracts\Auditable;

class Artikel extends Model implements Auditable
{
	use \OwenIt\Auditing\Auditable;
	
    protected $guarded = [];

    public function user()
    {
    	return $this->belongsTo('App\User');
    }
}

app/Http/Controllers/Api/ArtikelController.php
<?php

namespace App\Http\Controllers\Api;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Libs\Services\ArtikelService;

class ArtikelController extends Controller
{
    public function getArtikel(ArtikelService $service)
    {
        $artikel = $service->getAllArtikel();

    	$data = [];
    	foreach ($artikel as $key => $value) {
    		$data[] = $value;
    	}

    	return response()->json([
    		'status' => 'ok',
    		'data' => $data
    	]);
    }
}

app/Http/Controllers/ArtikelController.php
<?php

namespace App\Http\Controllers;

use App\Libs\Services\ArtikelService;
use Illuminate\Http\Request;
use Redirect;

class ArtikelController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(ArtikelService $service)
    {
        $data = $service->getAllArtikel();

        return view('artikel.index', ['data' => $data]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request, ArtikelService $service)
    {
        $data = $request->except(['_token']);
        if ( $request->has('photo') ) {
			$data['photo'] = $request->file('photo')->store('artikel');
        }
        $data['user_id'] = $request->user()->id;
        $data['status'] = 1;

        $service->createArtikel($data);

        return Redirect::to('artikel')->withSuccess('Berhasil menambah artikel');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id, ArtikelService $service)
    {
        $data = $service->getArtikelById($id);

        return response()->json($data, 200);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id, ArtikelService $service)
    {
        $data = $request->except(['_method', '_token', 'photo']);
        if ( $request->has('photo') ) {
        	$data['photo'] = $request->file('photo')->store('artikel');
        }

        $service->updateArtikel($data, $id);

        return Redirect::to('artikel')->withSuccess('Berhasil merubah artikel');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id, ArtikelService $service)
    {
        $service->deleteArtikel($id);

        return Redirect::to('artikel')->withSuccess('Berhasil menghapus artikel');
    }
}

resources/views/artikel/index.blade.php
@extends('layouts.gentellela')

@section('content')
<!-- page content -->
<div class="right_col" role="main">
	<div class="row">
		<div class="col-md-12 col-sm-12 col-xs-12 text-right">
  			<button class="btn btn-app"
  				data-toggle="modal"
  				data-target="#modal_add">
  				<i class="fa fa-plus"></i> Tambah
  			</button>
  		</div>
	</div>
	<div class="row">
  		<div class="col-md-12 col-sm-12 col-xs-12">
    		<div class="x_panel">
      			<div class="x_title">
        			<h2>Daftar Post/Artikel</h2>
        			<div class="clearfix"></div>
      			</div>
      			<div class="x_content">
        			<div class="dashboard-widget-content">
          				<div class="col-md-12 hidden-small">
	            			<table id="datatable-fixed-header" class="table table-striped table-bordered">
	                  			<thead>
	                				<tr>
	                  					<th>Judul</th>
	                  					<th>Ringkasan</th>
	                  					<th>Penulis</th>
	                  					<th width="80px">Action</th>
	                				</tr>
	              				</thead>
	              				<tbody>
	              				@foreach($data as $key => $value)
	                				<tr>
	                  					<td>{{ $value->judul }}</td>
	                  					<td>{{ $value->ringkasan }}</td>
	                  					<td>{{ $value->user->name }}</td>
	                  					<td>
	                  						<button class="btn btn-warning"
	  											data-toggle="modal"
	  											data-target="#modal_update"
	  											data-url="{{ route('artikel.update', $value->id) }}"
	  											data-show-url="{{ route('artikel.show', $value->id) }}"
	  											title="Ubah Data">
	  											<i class="fa fa-edit""></i>
	  										</button>
	  										<a
	  											href="{{ route('artikel.destroy', $value->id) }}"
	  											class="btn btn-danger helper"
	  											title="Hapus Data"
	  											data-method="delete"
	  											data-id="{{ $value->id }}"
	  											data-token="{{ csrf_token() }}">
	  											<i class="fa fa-trash" ></i>
	  										</a>
	                  					</td>
	                				</tr>
	              				@endforeach
	              				</tbody>
	            			</table>
          				</div>
        			</div>
      			</div>
    		</div>
		</div>
	</div>
</div>
<!-- /page content -->

<div id="modal_add" class="modal fade" role="dialog">
    <div class="modal-dialog modal-lg">
        <!-- Modal content-->
        <form action="{{ route('artikel.store') }}" id="form_add" method="post" class="modal-content" enctype="multipart/form-data">
            {{ csrf_field() }}

            <div class="modal-header bg-primary-600">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Tambah Data Post/Artikel</h4>
            </div>
            <div class="modal-body form-horizontal">
                <div class="form-group">
                    <label class="control-label col-sm-3">Judul*</label>
                    <div class="col-sm-9">
                    	<input id="judul_add" type="text" class="form-control" name="judul" value="{{ old('judul') }}" required>
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-sm-3">Ringkasan*</label>
                    <div class="col-sm-9">
                    	<textarea id="ringkasan_add" class="form-control" name="ringkasan" rows="3" maxlength="200" required>{{ old('ringkasan') }}</textarea>
                    	<p>(Max: 200 Kata)</p>
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-sm-3">Konten*</label>
                    <div class="col-sm-9">
                    	<textarea id="isi_add" class="form-control" name="isi" rows="5" required>{{ old('isi') }}</textarea>
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-sm-3">Photo</label>
                    <div class="col-sm-9">
                    	<input id="photo_add" type="file" class="form-control" name="photo" accept="image/*">
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-dismiss="modal"><b><i class="fa fa-close"></i></b> Batal</button>
                <button type="submit" class="btn btn-success"><b><i class="fa fa-save"></i></b> Simpan</button>
            </div>
        </form>
    </div>
</div>

<div id="modal_update" class="modal fade" role="dialog">
    <div class="modal-dialog modal-lg">
        <!-- Modal content-->
        <form id="form_update" method="post" class="modal-content" enctype="multipart/form-data">
            {{ csrf_field() }}

            <input type="hidden" name="_method" value="put">

            <div class="modal-header bg-primary-600">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Ubah Data Post/Artikel</h4>
            </div>
            <div class="modal-body form-horizontal">
                <div class="form-group">
                    <label class="control-label col-sm-3">Judul*</label>
                    <div class="col-sm-9">
                    	<input id="judul_update" type="text" class="form-control" name="judul" required>
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-sm-3">Ringkasan*</label>
                    <div class="col-sm-9">
                    	<textarea id="ringkasan_update" class="form-control" name="ringkasan" rows="3" maxlength="200" required></textarea>
                    	<p>(Max: 200 Kata)</p>
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-sm-3">Konten*</label>
                    <div class="col-sm-9">
                    	<textarea id="isi_update" class="form-control" name="isi" rows="5" required></textarea>
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-sm-3">Photo</label>
                    <div class="col-sm-9">
                    	<input id="photo_update" type="file" class="form-control" name="photo" accept="image/*">
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-dismiss="modal"><b><i class="fa fa-close"></i></b> Batal</button>
                <button type="submit" class="btn btn-success"><b><i class="fa fa-save"></i></b> Simpan</button>
            </div>
        </form>
    </div>
</div>
@endsection

@section('js')
@if( Session::has('success') )
	<script type="text/javascript">
		swal("Berhasil", "{{ Session::get('success') }}", "success");
	</script>
@endif
@if( $errors->any() )
	<script type="text/javascript">
		swal("Tidak dapat menyimpan data", "{{ Html::ul($errors->all()) }}", "error");
	</script>
@endif

<script>
  	$(document).ready(function(){
        $('#datatable-fixed-header').DataTable({
          	fixedHeader: true
        });
        $.ajax({
            url: "{{ asset('js/helper.js') }}", dataType: "script",
        });
  	});

    $('#modal_update').on('show.bs.modal', function(e){
    	var url = $(e.relatedTarget).data('url');
    	var show_url = $(e.relatedTarget).data('show-url');

    	$("#form_update").prop('action', url);
    	
    	$.ajax({
            type : 'get',
            url: show_url,
            success: function(data){
            	$("#judul_update").val(data['judul']);
            	$("#ringkasan_update").val(data['ringkasan']);
            	$("#isi_update").val(data['isi']);
            }
        });
	});
</script>
@endsection